DROP TABLE NODEDESCRIPTION;
DROP TABLE RELATIONDESCRIPTION;
DROP TABLE USERNODELIST;
DROP TABLE GRADELIST;
DROP TABLE RELATIONLIST;
DROP TABLE NODELIST;
DROP TABLE NODETYPE;
DROP TABLE USERLIST;


CREATE TABLE NODETYPE (
typeID INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30)
)ENGINE=INNODB;

CREATE TABLE NODELIST (
nodeID INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(64),
typeID INT,
FOREIGN KEY (typeID) REFERENCES NODETYPE (typeID)
)ENGINE=INNODB;

CREATE TABLE RELATIONLIST (
relationID INT AUTO_INCREMENT PRIMARY KEY,
parentID INT,
childID INT,
FOREIGN KEY (parentID) REFERENCES NODELIST (nodeID),
FOREIGN KEY (childID) REFERENCES NODELIST (nodeID)
)ENGINE=INNODB;

CREATE TABLE RELATIONDESCRIPTION (
relationID INT PRIMARY KEY,
description VARCHAR(140),
FOREIGN KEY (relationID) REFERENCES RELATIONLIST (relationID)
)ENGINE=INNODB;

CREATE TABLE NODEDESCRIPTION (
nodeID INT PRIMARY KEY,
description VARCHAR(140),
FOREIGN KEY (nodeID) REFERENCES NODELIST (nodeID)
)ENGINE=INNODB;

CREATE TABLE USERLIST (
userID INT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(64) NOT NULL,
password VARCHAR(64) NOT NULL
)ENGINE=INNODB;

CREATE TABLE USERNODELIST (
userNodeID INT AUTO_INCREMENT PRIMARY KEY,
userID INT NOT NULL,
nodeID INT NOT NULL,
FOREIGN KEY (userID) REFERENCES USERLIST (userID),
FOREIGN KEY (nodeID) REFERENCES RELATIONLIST (relationID)
)ENGINE=INNODB;

CREATE TABLE GRADELIST (
gradeID INT AUTO_INCREMENT PRIMARY KEY,
userID INT NOT NULL,
courseID INT NOT NULL,
grade INT NOT NULL,
FOREIGN KEY (userID) REFERENCES USERLIST (userID),
FOREIGN KEY (courseID) REFERENCES RELATIONLIST (relationID)
)ENGINE=INNODB;
