INSERT INTO NODETYPELIST (name) VALUES ("Discipline");
INSERT INTO NODETYPELIST (name) VALUES ("Course");
INSERT INTO NODETYPELIST (name) VALUES ("Location");
INSERT INTO NODETYPELIST (name) VALUES ("Course & Location");
