SET @name="Advanced Higher";
SET @desc="";
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 1, 130);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 2, 110);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 3, 90);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 4, 72);
SET @name="Higher";
SET @desc="";
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 1, 80);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 2, 65);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 3, 50);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 4, 36);
SET @name="SNC";
SET @desc="Scottish National Certificate (C is higest grade)";
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 1, 125);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 2, 100);
INSERT INTO QUALIFICATIONLIST (name, description, grade, points) VALUES (@name, @desc, 3, 75);
SET @name="";
SET @desc="";
