INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computing" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Computer Science" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computing" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Information Systems" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computing" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Computer Systems" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Chemistry" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Chemistry" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Chemistry" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Chemistry" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Mathematics" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Mathematics" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Mathematics" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Mathematics" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Biology" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Biology" AND typeID=2));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Physics" AND typeID=1), (SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics" AND typeID=2));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computer Science" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computer Science at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computer Science at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computer Science" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computer Science at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computer Science at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computer Science" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computer Science at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computer Science at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Information Systems" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Information Systems at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Information Systems at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Information Systems" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Information Systems at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Information Systems at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Information Systems" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Information Systems at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Information Systems at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computer Systems" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computer Systems at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computer Systems at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computer Systems" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computer Systems at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computer Systems at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computer Systems" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computer Systems at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computer Systems at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Chemistry at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Chemistry at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Chemistry at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Chemistry at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Chemistry at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Chemistry at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Pharmaceutical Chemistry at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Computational Chemistry at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Mathematics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Mathematics at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Mathematics at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Mathematics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Mathematics at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Mathematics at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Mathematics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Mathematics at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Mathematics at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Statistical Modelling at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Financial Mathematics at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Biology" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Biology at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Biology at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Biology" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Biology at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Biology at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Biology" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Biology at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Biology at Stirling University" AND typeID=4));

INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Heriot-Watt University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics at Heriot-Watt University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Edinburgh University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics at Edinburgh University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics" AND typeID=2), (SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics at Stirling University" AND typeID=4));
INSERT INTO NODERELATIONLIST (parentID, childID) VALUES ((SELECT nodeID FROM NODELIST WHERE name="Stirling University" AND typeID=3), (SELECT nodeID FROM NODELIST WHERE name="Theoretical Physics at Stirling University" AND typeID=4));
